### ISSUE TITLE
Создание таймера. Фоновая работа для таймера

### ISSUE THREAD

**Issue by Voviihb** [Voviihb/FeedAndEat#32]
1. Необходимо реализовать таймер, который будет работать в фоне и присылать уведомление / звонить, когда время подойдет к концу. Использовать для этого WorkManager? (Service уже несколько устарели)
2. Объединить это с экраном готовки

**Comment by Racher612** [comment]
3. Мне кажется необходимо, чтобы напоминание с таймером висело в панели уведомлений
